# -*- coding: utf-8 -*-
"""HW1_SayyedMoeinKazemi_98521396.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sT0Y3ucJCxzLPOpI8ubZQevv9ufUJDT
"""

from sys import setrecursionlimit,stdin
from threading import stack_size
from numpy import zeros
setrecursionlimit(10**6)
stack_size(2**27)
def func(n):
    arr = [0 for k in range(n+1)]
    for i in range(n + 1):
        if(i <= 2):
            arr[i] = i
        else:
            arr[i] = arr[i - 1] + (i - 1) * arr[i - 2]
    print(int(arr[n]))
n = int(input())
func(n)