# -*- coding: utf-8 -*-
"""HW1_SayyedMoeinKazemi_98521396.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sT0Y3ucJCxzLPOpI8ubZQevv9ufUJDT
"""

from sys import setrecursionlimit
from threading import stack_size
from numpy import zeros
setrecursionlimit(10**6)
stack_size(2**27)
def func(arr,n):
    NextGreaterThanPrevious = 1
    PreviousGreaterThanNext = 1
    for i in range(1,n):
        if (arr[i] > arr[i-1]):
            NextGreaterThanPrevious = PreviousGreaterThanNext + 1
        elif (arr[i] < arr[i-1]):
            PreviousGreaterThanNext = NextGreaterThanPrevious + 1
    print(max( NextGreaterThanPrevious , PreviousGreaterThanNext))
n = int(input())
arr = [int(i) for i in input().split()]
func(arr,n)