# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located ats
    https://colab.research.google.com/drive/1sNSO563XWcwLAlI57KocrwcedLJ7xy_0
"""
def func(V):
    coins = [1,5,10]
    a1 = 0
    a2 = 0
    a3 = 0
    if(V>=coins[2]):
      a1 = V//coins[2]
      V = V%coins[2]
    if(V>=coins[1]):
      a2 = V//coins[1]
      V = V%coins[1]
    if(V>=coins[0]):
      a3 = V//coins[0]
      V = V%coins[0]
    print(a1+a2+a3)
if __name__ == '__main__':
    n = int(input())
    func(n)