# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YKNVvIO-YrQJPjUT8fW6l-FHTQ3us3g
"""

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YKNVvIO-YrQJPjUT8fW6l-FHTQ3us3g
"""

from sys import setrecursionlimit
from threading import stack_size
setrecursionlimit(10**6)
stack_size(2**27)
n = int(input())
jobs = list()
tmp = list()
zenMenta = 0
while n != 0:
    jobs.insert(len(jobs)-1,list(map(int,input().split())))
    n-=1
m = len(jobs)
for i in range (m):
    if jobs[i][3] < jobs[i][0] or jobs[i][1] > jobs[i][2]: 
        pass
    if jobs[i][0] +jobs[i][1] <  jobs[i][2] + jobs[i][3]  :
        if jobs[i][0] > jobs[i][3]:
            zenMenta = zenMenta+ (jobs[i][0] - jobs[i][3])
        elif jobs[i][1] > jobs[i][2]:
            zenMenta= zenMenta + (jobs[i][2] - jobs[i][1])
    elif jobs[i][0] + jobs[i][1] == jobs[i][2] + jobs[i][3] :
        if jobs[i][0] + jobs[i][2] >=jobs[i][1] + jobs[i][3]:
            zenMenta = zenMenta+(jobs[i][0] - jobs[i][3])
        else:
            zenMenta = zenMenta + (jobs[i][2] - jobs[i][1])
    else:
        zenMenta= zenMenta + (jobs[i][0] + jobs[i][2])
        tmp.insert(len(tmp)-1,jobs[i][0]+jobs[i][1])
        tmp.insert(len(tmp)-1,jobs[i][2]+jobs[i][3])
def main():
    pass
if __name__ == '__main__':
    rare = zenMenta
    turn = 0
    x = 0
    if turn == 0:
        turn = 1
    tmp.sort()
    m = len(tmp)
    while x < m :
        rare = rare- tmp[x]
        x+=2
    print(rare)