my_image=imread('Pic.png');
A=grayslice(my_image,140);
imshow(A,gray(140));
##############################
A=grayslice(my_image,70);
##imshow(A,gray(70));
##############################
A=grayslice(my_image,20);
##imshow(A,gray(20));
